### ISSUE TITLE
 Outdated documentation all mnesia plugin api return 404 

### ISSUE THREAD

**Issue by unreal-asr** [emqx/emqx-auth-mnesia#45]
Hi,
I have setup a 3 nodes cluster of emqx (comunity edition) on GKE by official HELM Charts (v.4.2.2)
Everything works fine but all API described on official [documentation](https://docs.emqx.io/broker/latest/en/advanced/auth-mnesia.html) return 404 not found. 
User configured by container env or emqx_auth_mnesia.conf file works fine but API not work at all. 

  EMQX_AUTH__MNESIA__1__LOGIN: "test"
  EMQX_AUTH__MNESIA__1__PASSWORD: "test123"
  EMQX_AUTH__MNESIA__1__IS_SUPERUSER: false

Example:

curl -i --basic -u admin:public -X GET **http://<IP/DNS>:8081/api/v4/auth_user**   
HTTP/1.1 404 Not Found
content-length: 10
content-type: text/plain
date: Wed, 11 Nov 2020 10:29:54 GMT
server: Cowboy

Not found

curl -i --basic  -u admin:public -X GET **http://35.192.43.74:8081/api/v4/emqx_acl**  
HTTP/1.1 404 Not Found
content-length: 10
content-type: text/plain
date: Wed, 11 Nov 2020 10:42:27 GMT
server: Cowboy

Not found

The right API path now is /api/v4/mqtt_user and /api/v4/mqtt_acl
Outdated documentation [here](https://docs.emqx.io/broker/latest/en/advanced/auth-mnesia.html)

**Comment by umeat** [comment]
This is also true for version 4.2.8. The documentation for 4.2 says emqx_acl, but it's actually mqtt_acl as you said.

**Comment by Rory-Z** [comment]
@umeat @unreal-altran 
Our documentation has been updated to thank you for your feedback
